### ISSUE TITLE
use the api 

### ISSUE THREAD

**Issue by ischlo** [NicolaFerracin/michelin-stars-restaurants-api#3]
Hi Nicola, 
I was looking at the Michelin website to see if there were any raw versions of their restaurants data set for a small side project and came across your api instead. Is it on ? I would be happy to use it in case it is. 
Best,
Ivann Schlosser

**Comment by NicolaFerracin** [comment]
Hey Ivann!

Sorry for the late reply. Unfortunately the API is not currently working, there are some issues on the VPS where it's hosted and I haven't gotten around to look into it, and I'm not really sure I will. This was more of a side project/exercise than anything else.

If you are tech-savvy it shouldn't be too hard to run on your own, I'll be happy to give you some hints in case you need them.

**Comment by xexi81** [comment]
Hi!

Tell us something if you solve the API problems! I'd want to use it too! :)

Best regards!

**Comment by ischlo** [comment]
Hey, 
I managed to scrap the data from their website. depending on what exactly you were looking for I can send it to you, however, the descriptions are in French. I might set up a repo with the code and data if interested. Let me know,
Cheers
